services:
  - type: web
    name: fincalendar-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: YOOKASSA_SHOP_ID
        sync: false
      - key: YOOKASSA_SECRET_KEY
        sync: false
      - key: APP_URL
        sync: false
